Update static.mouse.rip command in release script

diff --git a/scripts/release b/scripts/release
--- a/scripts/release
+++ b/scripts/release
@@ -116,5 +116,13 @@ git checkout main
 
 # Update static.mouse.rip if the _update_static_mouse_rip command is available.
 if [ -n "$UPDATE_STATIC_MOUSE_RIP" ]; then
-  $UPDATE_STATIC_MOUSE_RIP
+  staticMouseRip=$($UPDATE_STATIC_MOUSE_RIP 2>&1)
+  if [ $? -ne 0 ]; then
+    echo "Failed to update static.mouse.rip"
+  else
+    echo "Updated static.mouse.rip"
+    echo "$staticMouseRip"
+  fi
+else
+  echo "No command available to update static.mouse.rip, export UPDATE_STATIC_MOUSE_RIP to enable"
 fi
